/**
 * Design Report Generator
 * Generates rich HTML reports from extracted design data
 */

import type { ExtractionResult, MiromiroDesignTokens, ExtractedAssets, AccessibilityReport } from './miromiro-types';

export class DesignReportGenerator {
    /**
     * Generate a complete HTML report
     */
    generateHTML(data: ExtractionResult): string {
        const { url, extractedAt } = data.metadata;
        const tokens = data.tokens;
        const assets = data.assets;
        const accessibility = data.accessibility;

        return `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Design Profile - ${url}</title>
  <style>
    :root {
      --primary: #5E6AD2;
      --bg: #F9FAFB;
      --surface: #FFFFFF;
      --text: #111827;
      --text-muted: #6B7280;
      --border: #E5E7EB;
      --radius: 8px;
    }

    * { box-sizing: border-box; }
    body {
      font-family: 'Inter', -apple-system, system-ui, sans-serif;
      line-height: 1.5;
      color: var(--text);
      background: var(--bg);
      margin: 0;
      padding: 40px;
    }

    .container {
      max-width: 900px;
      margin: 0 auto;
      background: var(--surface);
      padding: 60px;
      border-radius: 12px;
      box-shadow: 0 4px 24px rgba(0,0,0,0.05);
    }

    header {
      border-bottom: 2px solid var(--border);
      padding-bottom: 30px;
      margin-bottom: 40px;
    }

    .brand {
      font-weight: 800;
      font-size: 14px;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: var(--primary);
      margin-bottom: 10px;
    }

    h1 { margin: 0; font-size: 32px; font-weight: 700; }
    .metadata { color: var(--text-muted); font-size: 14px; margin-top: 5px; }

    section { margin-bottom: 50px; }
    h2 { font-size: 18px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; border-bottom: 1px solid var(--border); padding-bottom: 10px; margin-bottom: 25px; color: var(--text-muted); }

    /* Colors */
    .color-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 20px; }
    .color-card { border: 1px solid var(--border); border-radius: var(--radius); overflow: hidden; }
    .color-swatch { height: 80px; }
    .color-info { padding: 10px; font-size: 12px; }
    .color-hex { font-weight: 700; display: block; }
    .color-usage { color: var(--text-muted); }

    /* Typography */
    .typo-row { display: flex; align-items: baseline; margin-bottom: 20px; padding-bottom: 20px; border-bottom: 1px solid var(--bg); }
    .typo-label { width: 120px; font-size: 12px; color: var(--text-muted); }
    .typo-sample { flex: 1; }

    /* Assets */
    .asset-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 20px; }
    .asset-card { border: 1px solid var(--border); border-radius: var(--radius); padding: 15px; display: flex; align-items: center; justify-content: center; min-height: 120px; background: var(--bg); }
    .asset-card img { max-width: 100%; max-height: 100px; object-fit: contain; }
    .asset-card svg { max-width: 100%; max-height: 80px; }

    /* Accessibility */
    .score-badge { display: inline-block; padding: 10px 20px; border-radius: 30px; font-weight: 700; font-size: 24px; margin-bottom: 20px; }
    .score-high { background: #DCFCE7; color: #166534; }
    .score-medium { background: #FEF9C3; color: #854D0E; }
    .score-low { background: #FEE2E2; color: #991B1B; }

    .issue-list { list-style: none; padding: 0; }
    .issue-item { padding: 12px; background: var(--bg); border-left: 4px solid #EF4444; margin-bottom: 10px; font-size: 14px; }
    .issue-warning { border-left-color: #F59E0B; }

    @media print {
      body { padding: 0; background: white; }
      .container { box-shadow: none; max-width: 100%; }
    }
  </style>
</head>
<body>
  <div class="container">
    <header>
      <div class="brand">Taste Engine Design Profile</div>
      <h1>${new URL(url).hostname}</h1>
      <div class="metadata">Extracted on ${new Date(extractedAt).toLocaleDateString()} at ${new Date(extractedAt).toLocaleTimeString()}</div>
    </header>

    ${tokens ? this.renderTokens(tokens) : ''}
    ${assets ? this.renderAssets(assets) : ''}
    ${accessibility ? this.renderAccessibility(accessibility) : ''}

    <footer>
      <p style="text-align: center; color: #9CA3AF; font-size: 12px; margin-top: 60px;">Generated by Taste Engine UI Intelligence</p>
    </footer>
  </div>
</body>
</html>
    `;
    }

    private renderTokens(tokens: MiromiroDesignTokens): string {
        return `
    <section>
      <h2>Color Palette</h2>
      <div class="color-grid">
        ${tokens.colors.primary.slice(0, 4).map(c => this.renderColorCard(c, 'Primary')).join('')}
        ${tokens.colors.secondary.slice(0, 2).map(c => this.renderColorCard(c, 'Secondary')).join('')}
        ${tokens.colors.accent.slice(0, 2).map(c => this.renderColorCard(c, 'Accent')).join('')}
        ${tokens.colors.neutrals.slice(0, 4).map(c => this.renderColorCard(c, 'Neutral')).join('')}
      </div>
    </section>

    <section>
      <h2>Typography</h2>
      ${tokens.typography.headings.slice(0, 2).map(t => this.renderTypoRow(t, 'Heading')).join('')}
      ${tokens.typography.body.slice(0, 1).map(t => this.renderTypoRow(t, 'Body Text')).join('')}
      
      <div style="margin-top: 20px;">
        <span class="typo-label">Font Families:</span>
        <code style="background: #F3F4F6; padding: 4px 8px; border-radius: 4px; font-size: 13px;">
          ${tokens.typography.fontFamilies.join(', ')}
        </code>
      </div>
    </section>
    `;
    }

    private renderColorCard(color: any, label: string): string {
        return `
    <div class="color-card">
      <div class="color-swatch" style="background: ${color.value}"></div>
      <div class="color-info">
        <span class="color-hex">${color.value.toUpperCase()}</span>
        <span class="color-usage">${label}</span>
      </div>
    </div>
    `;
    }

    private renderTypoRow(typo: any, label: string): string {
        return `
    <div class="typo-row">
      <div class="typo-label">${label}</div>
      <div class="typo-sample" style="font-family: ${typo.fontFamily}; font-size: ${typo.fontSize}; font-weight: ${typo.fontWeight}; line-height: ${typo.lineHeight};">
        The quick brown fox jumps over the lazy dog.
      </div>
    </div>
    `;
    }

    private renderAssets(assets: ExtractedAssets): string {
        const images = assets.images.filter(img => img.category !== 'other').slice(0, 4);
        const svgs = assets.svgs.slice(0, 4);

        if (images.length === 0 && svgs.length === 0) return '';

        return `
    <section>
      <h2>Visual Assets</h2>
      <div class="asset-grid">
        ${images.map(img => `<div class="asset-card"><img src="${img.url}" alt="${img.alt || 'Asset'}"></div>`).join('')}
        ${svgs.map(svg => `<div class="asset-card">${svg.content}</div>`).join('')}
      </div>
    </section>
    `;
    }

    private renderAccessibility(accessibility: AccessibilityReport): string {
        const scoreClass = accessibility.score >= 90 ? 'score-high' : accessibility.score >= 70 ? 'score-medium' : 'score-low';

        return `
    <section>
      <h2>Accessibility Analysis</h2>
      <div class="score-badge ${scoreClass}">${accessibility.score} / 100 Score</div>
      
      <h3>Key Issues</h3>
      <ul class="issue-list">
        ${accessibility.wcag.issues.slice(0, 5).map(issue => `
          <li class="issue-item ${issue.severity === 'warning' ? 'issue-warning' : ''}">
            <strong>${issue.type.toUpperCase()}:</strong> ${issue.message} 
            <em style="color: #6B7280; font-size: 12px; display: block;">Element: ${issue.element || 'N/A'}</em>
          </li>
        `).join('')}
      </ul>
    </section>
    `;
    }
}
